const fileterRecipes = {
  recipes: [
    {
      id: '1',
      title: 'Paneer Butter Masala',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Paneer', 'Creamy', 'Gravy'],
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7',
      cookTime: 30,
      prepTime: 15,
      servings: 4,
      rating: 4.7,
      isVeg: true,
    },
    {
      id: '2',
      title: 'Spaghetti Carbonara',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Pasta', 'Cheese', 'Bacon'],
      imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3',
      cookTime: 20,
      prepTime: 10,
      servings: 2,
      rating: 4.5,
      isVeg: false,
    },
    {
      id: '3',
      title: 'Greek Salad',
      cuisine: 'mediterranean',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Fresh', 'Healthy', 'Feta'],
      imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe',
      cookTime: 0,
      prepTime: 15,
      servings: 2,
      rating: 4.2,
      isVeg: true,
    },
    {
      id: '4',
      title: 'Beef Tacos',
      cuisine: 'mexican',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'easy',
      tags: ['Meat', 'Spicy', 'Street Food'],
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47',
      cookTime: 20,
      prepTime: 20,
      servings: 3,
      rating: 4.6,
      isVeg: false,
    },
    {
      id: '5',
      title: 'Palak Paneer',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Spinach', 'Healthy', 'Paneer'],
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df056fb1d745',
      cookTime: 25,
      prepTime: 20,
      servings: 4,
      rating: 4.8,
      isVeg: true,
    },
    {
      id: '6',
      title: 'Chicken Alfredo',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Pasta', 'Creamy', 'Chicken'],
      imageUrl: 'https://images.unsplash.com/photo-1645112481338-35624bf8193a',
      cookTime: 25,
      prepTime: 15,
      servings: 2,
      rating: 4.7,
      isVeg: false,
    },
    {
      id: '7',
      title: 'Tofu Stir Fry',
      cuisine: 'chinese',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Tofu', 'Vegetables', 'Soy'],
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
      cookTime: 15,
      prepTime: 15,
      servings: 2,
      rating: 4.1,
      isVeg: true,
    },
    {
      id: '8',
      title: 'Mutton Rogan Josh',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'hard',
      tags: ['Lamb', 'Spicy', 'Rich'],
      imageUrl: 'https://images.unsplash.com/photo-1545242391-b45b23215ac6',
      cookTime: 90,
      prepTime: 30,
      servings: 4,
      rating: 4.9,
      isVeg: false,
    },
    {
      id: '9',
      title: 'Mushroom Risotto',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'hard',
      tags: ['Rice', 'Creamy', 'Mushroom'],
      imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371',
      cookTime: 45,
      prepTime: 15,
      servings: 3,
      rating: 4.4,
      isVeg: true,
    },
    {
      id: '10',
      title: 'Sushi Rolls',
      cuisine: 'japanese',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'hard',
      tags: ['Fish', 'Rice', 'Fresh'],
      imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
      cookTime: 40,
      prepTime: 45,
      servings: 2,
      rating: 4.8,
      isVeg: false,
    },
    {
      id: '11',
      title: 'Dal Tadka',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Lentils', 'Comfort', 'Spicy'],
      imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d',
      cookTime: 20,
      prepTime: 10,
      servings: 4,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '12',
      title: 'Grilled Salmon',
      cuisine: 'american',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Fish', 'Healthy', 'Grilled'],
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288',
      cookTime: 15,
      prepTime: 10,
      servings: 2,
      rating: 4.7,
      isVeg: false,
    },
    {
      id: '13',
      title: 'Classic Cheeseburger',
      cuisine: 'american',
      category: 'lunch',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Beef', 'Fast Food', 'Cheese'],
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd',
      cookTime: 15,
      prepTime: 20,
      servings: 1,
      rating: 4.5,
      isVeg: false,
    },
    {
      id: '14',
      title: 'Vegetable Quesadilla',
      cuisine: 'mexican',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Cheese', 'Quick', 'Tortilla'],
      imageUrl: 'https://images.unsplash.com/photo-1599974579688-8dbdd335c77f',
      cookTime: 10,
      prepTime: 10,
      servings: 2,
      rating: 4.3,
      isVeg: true,
    },
    {
      id: '15',
      title: 'Thai Green Curry',
      cuisine: 'thai',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Spicy', 'Coconut', 'Chicken'],
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd',
      cookTime: 30,
      prepTime: 20,
      servings: 3,
      rating: 4.6,
      isVeg: false,
    },
  ],
}

export default fileterRecipes
