const pantryitems = {
  items: [
    {
      id: 1,
      name: "Milk",
      quantity: "1 Gallon",
      category: "Dairy",
      expiryDate: "2026-04-10",
      expiryStatus: "fresh",
    },
    {
      id: 2,
      name: "Eggs",
      quantity: "1 Dozen",
      category: "Dairy",
      expiryDate: "2026-03-28",
      expiryStatus: "expiring_soon",
    },
    {
      id: 3,
      name: "Bread",
      quantity: "1 Loaf",
      category: "Bakery",
      expiryDate: "2026-03-20",
      expiryStatus: "expired",
    },
    {
      id: 4,
      name: "Jasmine Rice",
      quantity: "5 lbs",
      category: "Pantry Staples",
      expiryDate: "",
      expiryStatus: "no_expiry",
    },
    {
      id: 5,
      name: "Spinach",
      quantity: "1 Bag",
      category: "Produce",
      expiryDate: "2026-03-30",
      expiryStatus: "fresh",
    },
    {
      id: 6,
      name: "Chicken Breast",
      quantity: "2 lbs",
      category: "Meat",
      expiryDate: "2026-03-27",
      expiryStatus: "expiring_soon",
    },
    {
      id: 7,
      name: "Tomatoes",
      quantity: "3 medium",
      category: "Produce",
      expiryDate: "2026-03-29",
      expiryStatus: "fresh",
    },
    {
      id: 8,
      name: "Pasta",
      quantity: "1 box",
      category: "Pantry Staples",
      expiryDate: "",
      expiryStatus: "no_expiry",
    },
    {
      id: 9,
      name: "Yogurt",
      quantity: "4 cups",
      category: "Dairy",
      expiryDate: "2026-03-25",
      expiryStatus: "expired",
    },
    {
      id: 10,
      name: "Salmon",
      quantity: "1 fillet",
      category: "Meat",
      expiryDate: "2026-03-31",
      expiryStatus: "fresh",
    },
  ],
};

export default pantryitems;
