const quickmeals = {
  meals: [
    {
      id: '1',
      title: 'Butter Chicken',
      description: 'Juicy chicken in a rich buttery tomato gravy.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Chicken', 'Curry', 'Creamy'],
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398',
      cookTime: 40,
      prepTime: 20,
      servings: 4,
      rating: 4.8,
      isVeg: false,
    },
    {
      id: '2',
      title: 'Margherita Pizza',
      description: 'Classic pizza with tomato, mozzarella, and basil.',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Pizza', 'Cheese', 'Italian'],
      imageUrl: 'https://images.unsplash.com/photo-1601924928376-5b6e0d9e0b4c',
      cookTime: 25,
      prepTime: 15,
      servings: 2,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '3',
      title: 'Chicken Biryani',
      description: 'Aromatic rice with spicy marinated chicken.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'non-vegetarian',
      difficulty: 'hard',
      tags: ['Rice', 'Chicken', 'Spicy'],
      imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f',
      cookTime: 60,
      prepTime: 30,
      servings: 5,
      rating: 4.9,
      isVeg: false,
    },
    {
      id: '4',
      title: 'Veg Fried Rice',
      description: 'Stir-fried rice with vegetables and soy sauce.',
      cuisine: 'chinese',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Rice', 'Quick', 'Asian'],
      imageUrl: 'https://images.unsplash.com/photo-1604908812038-7d0c8b8e1a1c',
      cookTime: 20,
      prepTime: 10,
      servings: 3,
      rating: 4.3,
      isVeg: true,
    },
    {
      id: '5',
      title: 'Tandoori Chicken',
      description: 'Spicy grilled chicken marinated in yogurt and spices.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Grilled', 'Chicken', 'Spicy'],
      imageUrl: 'https://images.unsplash.com/photo-1604909053199-2a0fcbf6d5a3',
      cookTime: 45,
      prepTime: 25,
      servings: 4,
      rating: 4.7,
      isVeg: false,
    },
    {
      id: '6',
      title: 'Pasta Alfredo',
      description: 'Creamy white sauce pasta with garlic and cheese.',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Pasta', 'Creamy', 'Cheese'],
      imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023882c',
      cookTime: 25,
      prepTime: 10,
      servings: 2,
      rating: 4.5,
      isVeg: true,
    },
    {
      id: '7',
      title: 'Fish Curry',
      description: 'Tangy and spicy fish cooked in coconut gravy.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Fish', 'Curry', 'Coastal'],
      imageUrl: 'https://images.unsplash.com/photo-1627308595216-9d49d7a3c1f9',
      cookTime: 35,
      prepTime: 15,
      servings: 4,
      rating: 4.6,
      isVeg: false,
    },
    {
      id: '8',
      title: 'Veg Burger',
      description: 'Crispy vegetable patty in a soft bun.',
      cuisine: 'american',
      category: 'snack',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Burger', 'Fast Food', 'Snack'],
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349',
      cookTime: 15,
      prepTime: 10,
      servings: 2,
      rating: 4.2,
      isVeg: true,
    },
    {
      id: '9',
      title: 'Egg Omelette',
      description: 'Fluffy omelette with spices and veggies.',
      cuisine: 'global',
      category: 'breakfast',
      diet: 'non-vegetarian',
      difficulty: 'easy',
      tags: ['Egg', 'Quick', 'Protein'],
      imageUrl: 'https://images.unsplash.com/photo-1551218808-94e220e084d2',
      cookTime: 10,
      prepTime: 5,
      servings: 1,
      rating: 4.4,
      isVeg: false,
    },
    {
      id: '10',
      title: 'Chocolate Cake',
      description: 'Moist and rich chocolate layered cake.',
      cuisine: 'dessert',
      category: 'dessert',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Sweet', 'Cake', 'Chocolate'],
      imageUrl: 'https://images.unsplash.com/photo-1601972599720-36938d4ecd31',
      cookTime: 50,
      prepTime: 20,
      servings: 6,
      rating: 4.9,
      isVeg: true,
    },
  ],
}

export default quickmeals
