const quickmeals = {
  meals: [
    {
      id: '1',
      title: 'Butter Chicken',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'non-vegetarian',
      difficulty: 'medium',
      tags: ['Chicken', 'Curry', 'Creamy'],
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398',
      cookTime: 40,
      prepTime: 20,
      servings: 4,
      rating: 4.8,
      isVeg: false,
    },
    {
      id: '2',
      title: 'Margherita Pizza',
      imageUrl: 'https://images.unsplash.com/photo-1601924928376-5b6e0d9e0b4c',
      cuisine: 'italian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      cookTime: 25,
      prepTime: 15,
      servings: 2,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '3',
      title: 'Chicken Biryani',
      imageUrl: 'https://images.unsplash.com/photo-1627308595229-7830a5c91f9f',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'non-vegetarian',
      difficulty: 'hard',
      cookTime: 60,
      prepTime: 30,
      servings: 5,
      rating: 4.9,
      isVeg: false,
    },
    {
      id: '4',
      title: 'Veg Fried Rice',
      imageUrl: 'https://images.unsplash.com/photo-1604908812038-7d0c8b8e1a1c',
      cuisine: 'chinese',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      cookTime: 20,
      prepTime: 10,
      servings: 3,
      rating: 4.3,
      isVeg: true,
    },
  ],
}

export default quickmeals
