const recentlyviewed = {
  recipes: [
    {
      id: '1',
      title: 'Paneer Butter Masala',
      description:
        'A creamy, buttery curry with soft paneer in a rich tomato gravy.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Indian', 'Curry', 'Paneer', 'Vegetarian'],
      imageUrl: 'https://images.unsplash.com/photo-1690401767645-595de0e0e5f8',
      cookTime: 30,
      prepTime: 15,
      servings: 4,
      rating: 4.7,
      isVeg: true,
    },
    {
      id: '2',

      title: 'Chole Bhature',
      description: 'Spicy chickpea curry served with fluffy fried bread.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Indian', 'Chickpeas', 'Spicy'],
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
      cookTime: 40,
      prepTime: 20,
      servings: 4,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '3',
      title: 'Veg Biryani',
      description:
        'Fragrant basmati rice cooked with mixed vegetables and spices.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'hard',
      tags: ['Rice', 'Spicy', 'Indian'],
      imageUrl: 'https://images.unsplash.com/photo-1633945274309-2c16a0d7f6df',
      cookTime: 50,
      prepTime: 25,
      servings: 5,
      rating: 4.8,
      isVeg: true,
    },
    {
      id: '4',
      title: 'Masala Dosa',
      description: 'Crispy rice crepe filled with spiced potato filling.',
      cuisine: 'indian',
      category: 'breakfast',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Indian', 'Dosa', 'Breakfast'],
      imageUrl: 'https://images.unsplash.com/photo-1604908812038-7d0c8b8e1a1c',
      cookTime: 30,
      prepTime: 20,
      servings: 2,
      rating: 4.5,
      isVeg: true,
    },
  ],
}

export default recentlyviewed
