const trending = {
  recipes: [
    {
      id: '1',
      title: 'Paneer Butter Masala',
      description:
        'A creamy, buttery curry with soft paneer in a rich tomato gravy.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Indian', 'Curry', 'Paneer', 'Vegetarian'],
      imageUrl: 'https://images.unsplash.com/photo-1690401767645-595de0e0e5f8',
      cookTime: 30,
      prepTime: 15,
      servings: 4,
      rating: 4.7,
      isVeg: true,
    },
    {
      id: '2',
      title: 'Chole Bhature',
      description: 'Spicy chickpea curry served with fluffy fried bread.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Indian', 'Chickpeas', 'Spicy'],
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
      cookTime: 40,
      prepTime: 20,
      servings: 4,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '3',
      title: 'Veg Biryani',
      description:
        'Fragrant basmati rice cooked with mixed vegetables and spices.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'hard',
      tags: ['Rice', 'Spicy', 'Indian'],
      imageUrl: 'https://images.unsplash.com/photo-1633945274309-2c16a0d7f6df',
      cookTime: 50,
      prepTime: 25,
      servings: 5,
      rating: 4.8,
      isVeg: true,
    },
    {
      id: '4',
      title: 'Masala Dosa',
      description: 'Crispy rice crepe filled with spiced potato filling.',
      cuisine: 'indian',
      category: 'breakfast',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['South Indian', 'Dosa', 'Crispy'],
      imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3',
      cookTime: 25,
      prepTime: 20,
      servings: 3,
      rating: 4.5,
      isVeg: true,
    },
    {
      id: '5',
      title: 'Dal Tadka',
      description: 'Yellow lentils tempered with spices and ghee.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Dal', 'Healthy', 'Protein'],
      imageUrl: 'https://images.unsplash.com/photo-1626500154748-14b1c6a1c8e5',
      cookTime: 30,
      prepTime: 10,
      servings: 4,
      rating: 4.4,
      isVeg: true,
    },
    {
      id: '6',
      title: 'Aloo Paratha',
      description: 'Stuffed flatbread with spicy mashed potatoes.',
      cuisine: 'indian',
      category: 'breakfast',
      diet: 'vegetarian',
      difficulty: 'easy',
      tags: ['Paratha', 'Breakfast', 'Indian'],
      imageUrl: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56',
      cookTime: 20,
      prepTime: 15,
      servings: 3,
      rating: 4.6,
      isVeg: true,
    },
    {
      id: '7',
      title: 'Palak Paneer',
      description: 'Paneer cubes cooked in a smooth spinach gravy.',
      cuisine: 'indian',
      category: 'dinner',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Paneer', 'Healthy', 'Spinach'],
      imageUrl: 'https://images.unsplash.com/photo-1631515242808-497c3c5d5eaa',
      cookTime: 35,
      prepTime: 15,
      servings: 4,
      rating: 4.7,
      isVeg: true,
    },
    {
      id: '8',
      title: 'Rajma Chawal',
      description: 'Kidney bean curry served with steamed rice.',
      cuisine: 'indian',
      category: 'lunch',
      diet: 'vegetarian',
      difficulty: 'medium',
      tags: ['Rajma', 'Rice', 'Comfort Food'],
      imageUrl: 'https://images.unsplash.com/photo-1625944525903-bc5d7c0a9eaf',
      cookTime: 45,
      prepTime: 15,
      servings: 4,
      rating: 4.8,
      isVeg: true,
    },
  ],
}

export default trending
